"""add continuaton verification

Revision ID: 3f8532f8bac9
Revises: 426171258071
Create Date: 2025-11-30 21:03:49.150519

"""
# gave it wrong name lol, actually added description to teachers (as you can see below)
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8532f8bac9'
down_revision: Union[str, None] = '426171258071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'description')
    # ### end Alembic commands ###
