"""add continuaton verification

Revision ID: 426171258071
Revises: b86044ca2dee
Create Date: 2025-11-29 23:53:40.153373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426171258071'
down_revision: Union[str, None] = 'b86044ca2dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votecodes', sa.Column('continuation_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votecodes', 'continuation_key')
    # ### end Alembic commands ###
