"""add voting criteria

Revision ID: 4ade333fd6c3
Revises: 3f8532f8bac9
Create Date: 2025-12-03 19:40:59.594340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ade333fd6c3'
down_revision: Union[str, None] = '3f8532f8bac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('understandability', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('helpfulness', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('fairness', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('clarity', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('homework_amount', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('exam_difficulty', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('humor', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('character', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('style', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'style')
    op.drop_column('votes', 'character')
    op.drop_column('votes', 'humor')
    op.drop_column('votes', 'exam_difficulty')
    op.drop_column('votes', 'homework_amount')
    op.drop_column('votes', 'clarity')
    op.drop_column('votes', 'fairness')
    op.drop_column('votes', 'helpfulness')
    op.drop_column('votes', 'understandability')
    # ### end Alembic commands ###
