"""initial migration

Revision ID: b86044ca2dee
Revises: 
Create Date: 2025-11-26 23:09:06.191546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86044ca2dee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('gender', sa.Boolean(), nullable=False))
    op.add_column('teachers', sa.Column('subjects', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'subjects')
    op.drop_column('teachers', 'gender')
    # ### end Alembic commands ###
